# fly.toml app configuration file generated for shinyjourney on 2023-09-21T00:18:56+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "shinyjourney"
primary_region = "sin"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
