// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"shiny-journey/ent/attendance"
	"shiny-journey/ent/employee"
	"shiny-journey/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AttendanceUpdate is the builder for updating Attendance entities.
type AttendanceUpdate struct {
	config
	hooks    []Hook
	mutation *AttendanceMutation
}

// Where appends a list predicates to the AttendanceUpdate builder.
func (au *AttendanceUpdate) Where(ps ...predicate.Attendance) *AttendanceUpdate {
	au.mutation.Where(ps...)
	return au
}

// SetAttendanceDate sets the "attendance_date" field.
func (au *AttendanceUpdate) SetAttendanceDate(t time.Time) *AttendanceUpdate {
	au.mutation.SetAttendanceDate(t)
	return au
}

// SetCheckInTime sets the "check_in_time" field.
func (au *AttendanceUpdate) SetCheckInTime(t time.Time) *AttendanceUpdate {
	au.mutation.SetCheckInTime(t)
	return au
}

// SetNillableCheckInTime sets the "check_in_time" field if the given value is not nil.
func (au *AttendanceUpdate) SetNillableCheckInTime(t *time.Time) *AttendanceUpdate {
	if t != nil {
		au.SetCheckInTime(*t)
	}
	return au
}

// ClearCheckInTime clears the value of the "check_in_time" field.
func (au *AttendanceUpdate) ClearCheckInTime() *AttendanceUpdate {
	au.mutation.ClearCheckInTime()
	return au
}

// SetCheckOutTime sets the "check_out_time" field.
func (au *AttendanceUpdate) SetCheckOutTime(t time.Time) *AttendanceUpdate {
	au.mutation.SetCheckOutTime(t)
	return au
}

// SetNillableCheckOutTime sets the "check_out_time" field if the given value is not nil.
func (au *AttendanceUpdate) SetNillableCheckOutTime(t *time.Time) *AttendanceUpdate {
	if t != nil {
		au.SetCheckOutTime(*t)
	}
	return au
}

// ClearCheckOutTime clears the value of the "check_out_time" field.
func (au *AttendanceUpdate) ClearCheckOutTime() *AttendanceUpdate {
	au.mutation.ClearCheckOutTime()
	return au
}

// SetStatus sets the "status" field.
func (au *AttendanceUpdate) SetStatus(a attendance.Status) *AttendanceUpdate {
	au.mutation.SetStatus(a)
	return au
}

// SetEmployeeID sets the "employee_id" field.
func (au *AttendanceUpdate) SetEmployeeID(i int) *AttendanceUpdate {
	au.mutation.SetEmployeeID(i)
	return au
}

// SetNillableEmployeeID sets the "employee_id" field if the given value is not nil.
func (au *AttendanceUpdate) SetNillableEmployeeID(i *int) *AttendanceUpdate {
	if i != nil {
		au.SetEmployeeID(*i)
	}
	return au
}

// ClearEmployeeID clears the value of the "employee_id" field.
func (au *AttendanceUpdate) ClearEmployeeID() *AttendanceUpdate {
	au.mutation.ClearEmployeeID()
	return au
}

// SetEmployee sets the "employee" edge to the Employee entity.
func (au *AttendanceUpdate) SetEmployee(e *Employee) *AttendanceUpdate {
	return au.SetEmployeeID(e.ID)
}

// Mutation returns the AttendanceMutation object of the builder.
func (au *AttendanceUpdate) Mutation() *AttendanceMutation {
	return au.mutation
}

// ClearEmployee clears the "employee" edge to the Employee entity.
func (au *AttendanceUpdate) ClearEmployee() *AttendanceUpdate {
	au.mutation.ClearEmployee()
	return au
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (au *AttendanceUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, au.sqlSave, au.mutation, au.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (au *AttendanceUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *AttendanceUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *AttendanceUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (au *AttendanceUpdate) check() error {
	if v, ok := au.mutation.Status(); ok {
		if err := attendance.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Attendance.status": %w`, err)}
		}
	}
	return nil
}

func (au *AttendanceUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := au.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(attendance.Table, attendance.Columns, sqlgraph.NewFieldSpec(attendance.FieldID, field.TypeInt))
	if ps := au.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := au.mutation.AttendanceDate(); ok {
		_spec.SetField(attendance.FieldAttendanceDate, field.TypeTime, value)
	}
	if value, ok := au.mutation.CheckInTime(); ok {
		_spec.SetField(attendance.FieldCheckInTime, field.TypeTime, value)
	}
	if au.mutation.CheckInTimeCleared() {
		_spec.ClearField(attendance.FieldCheckInTime, field.TypeTime)
	}
	if value, ok := au.mutation.CheckOutTime(); ok {
		_spec.SetField(attendance.FieldCheckOutTime, field.TypeTime, value)
	}
	if au.mutation.CheckOutTimeCleared() {
		_spec.ClearField(attendance.FieldCheckOutTime, field.TypeTime)
	}
	if value, ok := au.mutation.Status(); ok {
		_spec.SetField(attendance.FieldStatus, field.TypeEnum, value)
	}
	if au.mutation.EmployeeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attendance.EmployeeTable,
			Columns: []string{attendance.EmployeeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.EmployeeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attendance.EmployeeTable,
			Columns: []string{attendance.EmployeeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{attendance.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	au.mutation.done = true
	return n, nil
}

// AttendanceUpdateOne is the builder for updating a single Attendance entity.
type AttendanceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AttendanceMutation
}

// SetAttendanceDate sets the "attendance_date" field.
func (auo *AttendanceUpdateOne) SetAttendanceDate(t time.Time) *AttendanceUpdateOne {
	auo.mutation.SetAttendanceDate(t)
	return auo
}

// SetCheckInTime sets the "check_in_time" field.
func (auo *AttendanceUpdateOne) SetCheckInTime(t time.Time) *AttendanceUpdateOne {
	auo.mutation.SetCheckInTime(t)
	return auo
}

// SetNillableCheckInTime sets the "check_in_time" field if the given value is not nil.
func (auo *AttendanceUpdateOne) SetNillableCheckInTime(t *time.Time) *AttendanceUpdateOne {
	if t != nil {
		auo.SetCheckInTime(*t)
	}
	return auo
}

// ClearCheckInTime clears the value of the "check_in_time" field.
func (auo *AttendanceUpdateOne) ClearCheckInTime() *AttendanceUpdateOne {
	auo.mutation.ClearCheckInTime()
	return auo
}

// SetCheckOutTime sets the "check_out_time" field.
func (auo *AttendanceUpdateOne) SetCheckOutTime(t time.Time) *AttendanceUpdateOne {
	auo.mutation.SetCheckOutTime(t)
	return auo
}

// SetNillableCheckOutTime sets the "check_out_time" field if the given value is not nil.
func (auo *AttendanceUpdateOne) SetNillableCheckOutTime(t *time.Time) *AttendanceUpdateOne {
	if t != nil {
		auo.SetCheckOutTime(*t)
	}
	return auo
}

// ClearCheckOutTime clears the value of the "check_out_time" field.
func (auo *AttendanceUpdateOne) ClearCheckOutTime() *AttendanceUpdateOne {
	auo.mutation.ClearCheckOutTime()
	return auo
}

// SetStatus sets the "status" field.
func (auo *AttendanceUpdateOne) SetStatus(a attendance.Status) *AttendanceUpdateOne {
	auo.mutation.SetStatus(a)
	return auo
}

// SetEmployeeID sets the "employee_id" field.
func (auo *AttendanceUpdateOne) SetEmployeeID(i int) *AttendanceUpdateOne {
	auo.mutation.SetEmployeeID(i)
	return auo
}

// SetNillableEmployeeID sets the "employee_id" field if the given value is not nil.
func (auo *AttendanceUpdateOne) SetNillableEmployeeID(i *int) *AttendanceUpdateOne {
	if i != nil {
		auo.SetEmployeeID(*i)
	}
	return auo
}

// ClearEmployeeID clears the value of the "employee_id" field.
func (auo *AttendanceUpdateOne) ClearEmployeeID() *AttendanceUpdateOne {
	auo.mutation.ClearEmployeeID()
	return auo
}

// SetEmployee sets the "employee" edge to the Employee entity.
func (auo *AttendanceUpdateOne) SetEmployee(e *Employee) *AttendanceUpdateOne {
	return auo.SetEmployeeID(e.ID)
}

// Mutation returns the AttendanceMutation object of the builder.
func (auo *AttendanceUpdateOne) Mutation() *AttendanceMutation {
	return auo.mutation
}

// ClearEmployee clears the "employee" edge to the Employee entity.
func (auo *AttendanceUpdateOne) ClearEmployee() *AttendanceUpdateOne {
	auo.mutation.ClearEmployee()
	return auo
}

// Where appends a list predicates to the AttendanceUpdate builder.
func (auo *AttendanceUpdateOne) Where(ps ...predicate.Attendance) *AttendanceUpdateOne {
	auo.mutation.Where(ps...)
	return auo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auo *AttendanceUpdateOne) Select(field string, fields ...string) *AttendanceUpdateOne {
	auo.fields = append([]string{field}, fields...)
	return auo
}

// Save executes the query and returns the updated Attendance entity.
func (auo *AttendanceUpdateOne) Save(ctx context.Context) (*Attendance, error) {
	return withHooks(ctx, auo.sqlSave, auo.mutation, auo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (auo *AttendanceUpdateOne) SaveX(ctx context.Context) *Attendance {
	node, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auo *AttendanceUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *AttendanceUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (auo *AttendanceUpdateOne) check() error {
	if v, ok := auo.mutation.Status(); ok {
		if err := attendance.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Attendance.status": %w`, err)}
		}
	}
	return nil
}

func (auo *AttendanceUpdateOne) sqlSave(ctx context.Context) (_node *Attendance, err error) {
	if err := auo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(attendance.Table, attendance.Columns, sqlgraph.NewFieldSpec(attendance.FieldID, field.TypeInt))
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Attendance.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := auo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, attendance.FieldID)
		for _, f := range fields {
			if !attendance.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != attendance.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := auo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := auo.mutation.AttendanceDate(); ok {
		_spec.SetField(attendance.FieldAttendanceDate, field.TypeTime, value)
	}
	if value, ok := auo.mutation.CheckInTime(); ok {
		_spec.SetField(attendance.FieldCheckInTime, field.TypeTime, value)
	}
	if auo.mutation.CheckInTimeCleared() {
		_spec.ClearField(attendance.FieldCheckInTime, field.TypeTime)
	}
	if value, ok := auo.mutation.CheckOutTime(); ok {
		_spec.SetField(attendance.FieldCheckOutTime, field.TypeTime, value)
	}
	if auo.mutation.CheckOutTimeCleared() {
		_spec.ClearField(attendance.FieldCheckOutTime, field.TypeTime)
	}
	if value, ok := auo.mutation.Status(); ok {
		_spec.SetField(attendance.FieldStatus, field.TypeEnum, value)
	}
	if auo.mutation.EmployeeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attendance.EmployeeTable,
			Columns: []string{attendance.EmployeeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.EmployeeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attendance.EmployeeTable,
			Columns: []string{attendance.EmployeeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Attendance{config: auo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{attendance.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	auo.mutation.done = true
	return _node, nil
}
