// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"shiny-journey/ent/attendance"
	"shiny-journey/ent/employee"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AttendanceCreate is the builder for creating a Attendance entity.
type AttendanceCreate struct {
	config
	mutation *AttendanceMutation
	hooks    []Hook
}

// SetAttendanceDate sets the "attendance_date" field.
func (ac *AttendanceCreate) SetAttendanceDate(t time.Time) *AttendanceCreate {
	ac.mutation.SetAttendanceDate(t)
	return ac
}

// SetCheckInTime sets the "check_in_time" field.
func (ac *AttendanceCreate) SetCheckInTime(t time.Time) *AttendanceCreate {
	ac.mutation.SetCheckInTime(t)
	return ac
}

// SetNillableCheckInTime sets the "check_in_time" field if the given value is not nil.
func (ac *AttendanceCreate) SetNillableCheckInTime(t *time.Time) *AttendanceCreate {
	if t != nil {
		ac.SetCheckInTime(*t)
	}
	return ac
}

// SetCheckOutTime sets the "check_out_time" field.
func (ac *AttendanceCreate) SetCheckOutTime(t time.Time) *AttendanceCreate {
	ac.mutation.SetCheckOutTime(t)
	return ac
}

// SetNillableCheckOutTime sets the "check_out_time" field if the given value is not nil.
func (ac *AttendanceCreate) SetNillableCheckOutTime(t *time.Time) *AttendanceCreate {
	if t != nil {
		ac.SetCheckOutTime(*t)
	}
	return ac
}

// SetStatus sets the "status" field.
func (ac *AttendanceCreate) SetStatus(a attendance.Status) *AttendanceCreate {
	ac.mutation.SetStatus(a)
	return ac
}

// SetEmployeeID sets the "employee" edge to the Employee entity by ID.
func (ac *AttendanceCreate) SetEmployeeID(id int) *AttendanceCreate {
	ac.mutation.SetEmployeeID(id)
	return ac
}

// SetNillableEmployeeID sets the "employee" edge to the Employee entity by ID if the given value is not nil.
func (ac *AttendanceCreate) SetNillableEmployeeID(id *int) *AttendanceCreate {
	if id != nil {
		ac = ac.SetEmployeeID(*id)
	}
	return ac
}

// SetEmployee sets the "employee" edge to the Employee entity.
func (ac *AttendanceCreate) SetEmployee(e *Employee) *AttendanceCreate {
	return ac.SetEmployeeID(e.ID)
}

// Mutation returns the AttendanceMutation object of the builder.
func (ac *AttendanceCreate) Mutation() *AttendanceMutation {
	return ac.mutation
}

// Save creates the Attendance in the database.
func (ac *AttendanceCreate) Save(ctx context.Context) (*Attendance, error) {
	return withHooks(ctx, ac.sqlSave, ac.mutation, ac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ac *AttendanceCreate) SaveX(ctx context.Context) *Attendance {
	v, err := ac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ac *AttendanceCreate) Exec(ctx context.Context) error {
	_, err := ac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ac *AttendanceCreate) ExecX(ctx context.Context) {
	if err := ac.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ac *AttendanceCreate) check() error {
	if _, ok := ac.mutation.AttendanceDate(); !ok {
		return &ValidationError{Name: "attendance_date", err: errors.New(`ent: missing required field "Attendance.attendance_date"`)}
	}
	if _, ok := ac.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Attendance.status"`)}
	}
	if v, ok := ac.mutation.Status(); ok {
		if err := attendance.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Attendance.status": %w`, err)}
		}
	}
	return nil
}

func (ac *AttendanceCreate) sqlSave(ctx context.Context) (*Attendance, error) {
	if err := ac.check(); err != nil {
		return nil, err
	}
	_node, _spec := ac.createSpec()
	if err := sqlgraph.CreateNode(ctx, ac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	ac.mutation.id = &_node.ID
	ac.mutation.done = true
	return _node, nil
}

func (ac *AttendanceCreate) createSpec() (*Attendance, *sqlgraph.CreateSpec) {
	var (
		_node = &Attendance{config: ac.config}
		_spec = sqlgraph.NewCreateSpec(attendance.Table, sqlgraph.NewFieldSpec(attendance.FieldID, field.TypeInt))
	)
	if value, ok := ac.mutation.AttendanceDate(); ok {
		_spec.SetField(attendance.FieldAttendanceDate, field.TypeTime, value)
		_node.AttendanceDate = value
	}
	if value, ok := ac.mutation.CheckInTime(); ok {
		_spec.SetField(attendance.FieldCheckInTime, field.TypeTime, value)
		_node.CheckInTime = &value
	}
	if value, ok := ac.mutation.CheckOutTime(); ok {
		_spec.SetField(attendance.FieldCheckOutTime, field.TypeTime, value)
		_node.CheckOutTime = &value
	}
	if value, ok := ac.mutation.Status(); ok {
		_spec.SetField(attendance.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if nodes := ac.mutation.EmployeeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attendance.EmployeeTable,
			Columns: []string{attendance.EmployeeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.employee_attendances = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AttendanceCreateBulk is the builder for creating many Attendance entities in bulk.
type AttendanceCreateBulk struct {
	config
	builders []*AttendanceCreate
}

// Save creates the Attendance entities in the database.
func (acb *AttendanceCreateBulk) Save(ctx context.Context) ([]*Attendance, error) {
	specs := make([]*sqlgraph.CreateSpec, len(acb.builders))
	nodes := make([]*Attendance, len(acb.builders))
	mutators := make([]Mutator, len(acb.builders))
	for i := range acb.builders {
		func(i int, root context.Context) {
			builder := acb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AttendanceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, acb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, acb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, acb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (acb *AttendanceCreateBulk) SaveX(ctx context.Context) []*Attendance {
	v, err := acb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (acb *AttendanceCreateBulk) Exec(ctx context.Context) error {
	_, err := acb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acb *AttendanceCreateBulk) ExecX(ctx context.Context) {
	if err := acb.Exec(ctx); err != nil {
		panic(err)
	}
}
