// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Admin is the predicate function for admin builders.
type Admin func(*sql.Selector)

// Attendance is the predicate function for attendance builders.
type Attendance func(*sql.Selector)

// Employee is the predicate function for employee builders.
type Employee func(*sql.Selector)
